In [12]:
import arviz as az
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pymc as pm
import pytensor
import pytensor.tensor as pt

from numba import njit
from pymc.ode import DifferentialEquation
from pytensor.compile.ops import as_op
from scipy.integrate import odeint
from scipy.optimize import least_squares
from scipy.optimize import leastsq

from sklearn import linear_model
from numpy.linalg import norm

from numpy import dot
from numpy.linalg import norm

import statistics

import warnings
warnings.filterwarnings('ignore')

import random
random.seed(10)

In [4]:
random.seed(10)
true_para = np.array([0.31, -0.6, 0.29, -0.01, 0.011, 0.009, -0.01, -0.012, 0.015, 0.3, 0.5, 0.2, 100])
#true_para = np.array([0.21, -0.4, 0.19, -0.02, 0.016, 0.01, -0.014, -0.017, 0.02, 0.3, 0.5, 0.2, 100])
time_seg = 0.5
cur_time = np.arange(0, 10+time_seg, time_seg)
num_point = len(cur_time)

# define the right hand side of the ODE equations in the Scipy odeint signature
from numba import njit


@njit
def rhs(X, t, theta):
    # unpack parameters
    x, y, z, n = X
    r1, r2, r3, b12, b13, b21, b23, b31, b32, x0, y0, z0, n0 = theta
    # equations
    dn_dt = r1*x*n + b12*x*y*n*n + b13*x*z*n*n + r2*y*n + b21*x*y*n*n + b23*y*z*n*n + r3*z*n + b31*x*z*n*n + b32*y*z*n*n
    dx_dt = (r1*x*n + b12*x*y*n*n + b13*x*z*n*n - x*dn_dt)/n
    dy_dt = (r2*y*n + b21*x*y*n*n + b23*y*z*n*n - y*dn_dt)/n
    dz_dt = (r3*z*n + b31*x*z*n*n + b32*y*z*n*n - z*dn_dt)/n
    return [dx_dt, dy_dt, dz_dt, dn_dt]
    
# note theta = alpha, beta, gamma, delta, xt0, yt0
theta = true_para
time = cur_time

# call Scipy's odeint function, 
x_y = odeint(func=rhs, y0=theta[-4:], t=time, args=(theta,))
    
real_value = pd.DataFrame(dict(
    n1_relative = np.array(x_y[:, 0]),
    n2_relative = np.array(x_y[:, 1]),
    n3_relative = np.array(x_y[:, 2]),
    ))

real_value

    n1_relative  n2_relative  n3_relative
0      0.300000     0.500000     0.200000
1      0.331592     0.391974     0.276435
2      0.382216     0.289038     0.328746
3      0.452844     0.207820     0.339337
4      0.541084     0.152609     0.306307
5      0.637722     0.119947     0.242331
6      0.727029     0.104658     0.168313
7      0.793122     0.103172     0.103705
8      0.827187     0.114587     0.058226
9      0.827956     0.140798     0.031247
10     0.796738     0.186021     0.017241
11     0.734669     0.254527     0.010803
12     0.646397     0.345036     0.008567
13     0.545822     0.444972     0.009206
14     0.452968     0.533876     0.013156
15     0.382452     0.594805     0.022743
16     0.338313     0.619288     0.042399
17     0.318194     0.604192     0.077614
18     0.318480     0.550556     0.130965
19     0.336660     0.467025     0.196315
20     0.371838     0.370842     0.257320

In [13]:
select_dom = pd.DataFrame(dict(
    n1_relative = np.array(real_value.iloc[:, 0]),
    n2_relative = np.array(real_value.iloc[:, 1]),
    n3_relative = np.array(real_value.iloc[:, 2]),
))
for i in range (num_point-1):
    select_dom.loc[num_point+i] = (1/time_seg)*np.log(select_dom.loc[i+1]) - (1/time_seg)*np.log(select_dom.loc[i])


statistics.variance(select_dom.iloc[-num_point+1:, 0])

0.061069634924567295

In [14]:
statistics.variance(select_dom.iloc[-num_point+1:, 1])

0.20024292333109436

In [15]:
statistics.variance(select_dom.iloc[-num_point+1:, 2])

0.7596597972802089

In [18]:
data = pd.DataFrame(dict(
    n1_relative = np.array(real_value.iloc[:, 0]),
    n2_over_n1 = np.array(real_value.iloc[:, 1])/np.array(real_value.iloc[:, 0]),
    n3_over_n1 = np.array(real_value.iloc[:, 2])/np.array(real_value.iloc[:, 0]),
))
for i in range (num_point-1):
     data.loc[num_point+i] = (1/time_seg)*np.log(data.loc[i+1])- (1/time_seg)*np.log(data.loc[i]) 

data

    n1_relative  n2_over_n1  n3_over_n1
0      0.300000    1.666667    0.666667
1      0.331592    1.182097    0.833660
2      0.382216    0.756218    0.860105
3      0.452844    0.458922    0.749347
4      0.541084    0.282044    0.566099
5      0.637722    0.188086    0.379994
6      0.727029    0.143953    0.231508
7      0.793122    0.130084    0.130756
8      0.827187    0.138526    0.070390
9      0.827956    0.170055    0.037740
10     0.796738    0.233478    0.021639
11     0.734669    0.346452    0.014705
12     0.646397    0.533784    0.013254
13     0.545822    0.815234    0.016867
14     0.452968    1.178617    0.029045
15     0.382452    1.555239    0.059467
16     0.338313    1.830521    0.125325
17     0.318194    1.898816    0.243922
18     0.318480    1.728700    0.411218
19     0.336660    1.387228    0.583124
20     0.371838    0.997320    0.692021
21     0.200244   -0.687071    0.447070
22     0.284162   -0.893432    0.062458
23     0.339122   -0.998899   -0.275705
24     0.356056   -0.973636   -0.560867
25     0.328657   -0.810319   -0.797225
26     0.262128   -0.534837   -0.991087
27     0.174021   -0.202609   -1.142559
28     0.084107    0.125764   -1.238560
29     0.001858    0.410117   -1.246684
30    -0.076866    0.633937   -1.112418
31    -0.162212    0.789312   -0.772637
32    -0.256014    0.864495   -0.207809
33    -0.338242    0.846967    0.482110
34    -0.372942    0.737244    1.087023
35    -0.338436    0.554576    1.433151
36    -0.245266    0.325943    1.490973
37    -0.122619    0.073260    1.331878
38     0.001795   -0.187722    1.044554
39     0.111033   -0.440124    0.698553
40     0.198769   -0.659983    0.342433

In [19]:
#r1, r2, r3, b12, b13, b21, b23, b31, b32 = 1, 1, 1, 1, 1, 1, 1, 1, 1

df = pd.DataFrame(dict(
    n1_relative = np.array(real_value.iloc[:-1, 0]),
    n2_relative = np.array(real_value.iloc[:-1, 1]),
    n3_relative = np.array(real_value.iloc[:-1, 2]),
    delta_1 = np.array(data.iloc[num_point:, 0]),
    delta_2 = np.array(data.iloc[num_point:, 1]),
    delta_3 = np.array(data.iloc[num_point:, 2]),
))
df

    n1_relative  n2_relative  n3_relative   delta_1   delta_2   delta_3
0      0.300000     0.500000     0.200000  0.200244 -0.687071  0.447070
1      0.331592     0.391974     0.276435  0.284162 -0.893432  0.062458
2      0.382216     0.289038     0.328746  0.339122 -0.998899 -0.275705
3      0.452844     0.207820     0.339337  0.356056 -0.973636 -0.560867
4      0.541084     0.152609     0.306307  0.328657 -0.810319 -0.797225
5      0.637722     0.119947     0.242331  0.262128 -0.534837 -0.991087
6      0.727029     0.104658     0.168313  0.174021 -0.202609 -1.142559
7      0.793122     0.103172     0.103705  0.084107  0.125764 -1.238560
8      0.827187     0.114587     0.058226  0.001858  0.410117 -1.246684
9      0.827956     0.140798     0.031247 -0.076866  0.633937 -1.112418
10     0.796738     0.186021     0.017241 -0.162212  0.789312 -0.772637
11     0.734669     0.254527     0.010803 -0.256014  0.864495 -0.207809
12     0.646397     0.345036     0.008567 -0.338242  0.846967  0.482110
13     0.545822     0.444972     0.009206 -0.372942  0.737244  1.087023
14     0.452968     0.533876     0.013156 -0.338436  0.554576  1.433151
15     0.382452     0.594805     0.022743 -0.245266  0.325943  1.490973
16     0.338313     0.619288     0.042399 -0.122619  0.073260  1.331878
17     0.318194     0.604192     0.077614  0.001795 -0.187722  1.044554
18     0.318480     0.550556     0.130965  0.111033 -0.440124  0.698553
19     0.336660     0.467025     0.196315  0.198769 -0.659983  0.342433

In [5]:
def model_resid(params):
    r1, r2, r3, b12, b13, b21, b23, b31, b32 = params
    return (
         np.abs(df[["delta_1", "delta_2", "delta_3"]] -pd.DataFrame(dict(
            n1 = r1 + b12*np.array(real_value.iloc[:-1, 1]) + b13*np.array(real_value.iloc[:-1, 2]),
            n2 = r2 + b21*np.array(real_value.iloc[:-1, 0]) + b23*np.array(real_value.iloc[:-1, 2]),
            n3 = r3 + b31*np.array(real_value.iloc[:-1, 0]) + b32*np.array(real_value.iloc[:-1, 1]))))
     ).values.flatten()

#results = least_squares(model_resid, x0=np.array([0.21, -0.4, 0.19, -0.02, 0.016, 0.01, -0.014, -0.017, 0.02]), method = 'trf')
#results = leastsq(model_resid, x0=np.array([0.21, -0.4, 0.19, -0.02, 0.016, 0.01, -0.014, -0.017, 0.02]))

In [23]:
x = pd.DataFrame(dict(
    n2 = np.array(real_value.iloc[:-1, 0]),
    n3 = np.array(real_value.iloc[:-1, 2])
    ))
y = df[["delta_2"]]
regr = linear_model.LinearRegression()
regr.fit(x, y)
r2_est = regr.intercept_[0]
b21_est = regr.coef_[0,0]
b23_est = regr.coef_[0,1]


x = pd.DataFrame(dict(
    n2 = np.array(real_value.iloc[:-1, 0]),
    n3 = np.array(real_value.iloc[:-1, 1])
    ))
y = df[["delta_3"]]
regr = linear_model.LinearRegression()
regr.fit(x, y)
r3_est = regr.intercept_[0]
b31_est = regr.coef_[0,0]
b32_est = regr.coef_[0,1]

print(b21_est, b23_est, b31_est, b32_est)

0.9645253515925026 -4.728041283778571 0.870084823175046 5.60490841476626

In [7]:
theta_b = np.array([r1_est, r2_est, r3_est, b12_est, b13_est, b21_est, b23_est, b31_est, b32_est, 0.02, 0.3, 0.5, 0.2, 100])
theta_b

array([-9.16183803e-02, -1.01048130e-01, -7.66373208e-02, -7.46449158e-02,
        9.59115648e-01,  3.31562475e-01, -6.89811817e-01, -6.22586438e-02,
        3.43948747e-01,  2.00000000e-02,  3.00000000e-01,  5.00000000e-01,
        2.00000000e-01,  1.00000000e+02])

In [8]:
cosineb = dot(theta_b[3:9], true_para[3:9])/(norm(theta_b[3:9])*norm(true_para[3:9]))
cosineb

0.7632305902591541

In [9]:
time = cur_time

x_y = odeint(func=rhs, y0=theta_b[-3:], t=time, args=(theta_b,))

ValueError:

In [ ]:
# plot model function
def plot_model(
    ax,
    x_y,
    time=cur_time,
    alpha=0.2,
    lw=0.6,
):
    ax.plot(time, x_y[:, 0], color="red", alpha=alpha, lw=lw, label="N1")
    ax.plot(time, x_y[:, 1], color="blue", alpha=alpha, lw=lw, label="N2")
    ax.plot(time, x_y[:, 1], color="green", alpha=alpha, lw=lw, label="N3")
    ax.legend(fontsize=14, loc="center left", bbox_to_anchor=(1, 0.5))
    return ax
    

# plot data function for reuse later
def plot_data(ax, lw=0.1):
    ax.plot(cur_time, real_value.n1_relative, color="red", lw=lw, marker="o", markersize=2, label="N1")
    ax.plot(cur_time, real_value.n2_relative, color="blue", lw=lw, marker="+", markersize=2, label="N2")
    ax.plot(cur_time, real_value.n3_relative, color="green", lw=lw, marker="^", markersize=2, label="N3")
    ax.legend(fontsize=14, loc="center left", bbox_to_anchor=(1, 0.5))
    ax.set_xlim([0, len(cur_time)*time_seg])
    ax.set_xlabel("Time", fontsize=14)
    ax.set_ylabel("Relative abundance", fontsize=14)
    ax.set_xticks(df.year.astype(int))
    ax.set_xticklabels(ax.get_xticks(), rotation=45)
    return ax

In [ ]:
theta_b = np.array([r1_est, r2_est, r3_est, b12_est, b13_est, b21_est, b23_est, b31_est, b32_est, 0.02, 0.3, 0.5, 0.2, 100])
time = cur_time

x_y = odeint(func=rhs, y0=theta_b[-3:], t=time, args=(theta_b,))

# plot
_, ax = plt.subplots(figsize=(12, 4))
plot_model(ax, x_y);
plot_data(ax, lw=0.6)